version: "0.1.0.{build}"
environment:
  matrix:
  - TARGET: nightly-x86_64-pc-windows-msvc
  - TARGET: nightly-i686-pc-windows-msvc
  - TARGET: nightly-x86_64-pc-windows-gnu
  - TARGET: nightly-i686-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV
  - erase rust-install.exe
  - ps: Start-FileDownload "http://downloads.sourceforge.net/project/libusb/libusb-1.0/libusb-1.0.20/libusb-1.0.20.7z?use_mirror=heanet" -FileName "libusb.7z"
  - ps: 7z x -oc:\lib libusb.7z
  - erase libusb.7z
  - mkdir c:\.cargo
  - copy util\cargo-config-win.toml c:\.cargo\config
build_script:
  - cargo build
  - cargo package
skip_commits:
  files:
    - README.md
    - .travis.yml
    - appveyor.yml
