trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

stages:
 - template: default.yml@templates
   parameters:
     # Turn off feature checking since this is a workspace
     check_all_features: false
     check_no_features: false
     # cross: true
     minrust: false

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/master
      endpoint: qdot
