[package]
name = "buttplug"
version = "0.0.1"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Cross Platform Sex Toy Control Server"
license = "BSD-3-Clause"
homepage = "http://buttplug.io"
repository = "https://github.com/buttplugio/buttplug-rs.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]

[dependencies]
clap = {version = "2", features = ["yaml"]}
ws = "^0.5.3"
serde_json = "0.8"
serde_derive = "0.8"
serde = "0.8"
bytes = "^0.3.0"
mio = "0.6"
env_logger = "*"
log = "*"
# Device dependencies. Uncomment when devices actually start appearing in the
# codebase. Wastes build/CI times otherwise.
#
# libtrancevibe = "^0.1.0"
# lovesense = "^0.1.0"
