[package]
name = "buttplug_server"
version = "10.0.0"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Buttplug Intimate Hardware Control Library - Core Library"
license = "BSD-3-Clause"
homepage = "http://buttplug.io"
repository = "https://github.com/buttplugio/buttplug.git"
readme = "./README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2024"
exclude = ["examples/**"]

[lib]
name = "buttplug_server"
path = "src/lib.rs"
test = true
doctest = true
doc = true
crate-type = ["cdylib", "rlib"]

[features]
default=[]
wasm=["uuid/js"]

[dependencies]
buttplug_derive = "0.8.1"
buttplug_core = { path = "../buttplug_core" }
buttplug_server_device_config = { path = "../buttplug_server_device_config" }
# buttplug_derive = { path = "../buttplug_derive" }
futures = "0.3.31"
futures-util = "0.3.31"
thiserror = "2.0.12"
log = "0.4.27"
getset = "0.1.6"
tokio = { version = "1.46.1", features = ["macros"] }
dashmap = { version = "6.1.0" }
tracing-futures = "0.2.5"
tracing = "0.1.41"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
jsonschema = { version = "0.30.0", default-features = false }
once_cell = "1.21.3"
tokio-stream = "0.1.17"
strum_macros = "0.27.1"
strum = "0.27.1"
uuid = { version = "1.17.0", features = ["serde", "v4"] }
async-trait = "0.1.88"
instant = "0.1.13"
tokio-util = "0.7.15"
regex = "1.11.1"
prost = "0.14.1"
paste = "1.0.15"
aes = { version = "0.8.4" }
ecb = { version = "0.1.2", features = ["std"] }
sha2 = { version = "0.10.9", features = ["std"] }
byteorder = "1.5.0"
# Used by several packages, but we need to bring in the JS feature for wasm. Pinned at 0.2 until dependencies update
rand = { version = "0.8" }

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.3.3", features = ["wasm_js"]}
getrandom_old = { version = "0.2.15", features = ["js"], package = "getrandom"}