language: node_js
sudo: false
node_js:
- 9
install:
- yarn
script:
- yarn build
cache:
  - yarn
deploy:
- provider: pages
  local_dir: _book
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    repo: metafetish/buttplug
    branch: master
